config/routes.rb
Rails.application.routes.draw do
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'games#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index

    if params[:game_search]
      game_search_term = params[:game_search]
      mechanize = Mechanize.new

      # INSTANT GAMING SEARCH
      instant_game_page = mechanize.get('https://www.instant-gaming.com/it/')
      search_input = instant_game_page.forms.first
      search_input['q'] = game_search_term
      instant_game_page = search_input.submit
      results = instant_game_page.at('.search')
      games = results.search('.item')

      count_elements = 0
      @instant_game_array = []

      games.each do |game|

        game_price = game.at('.price').text.strip
        game_name = game.at('.name').text.strip
        game_platform = game.at('.badge').attr('class').remove('badge').strip
        game_link = game.at('.cover')["href"]
        game_image = game.at('.picture.mainshadow')["src"]

        hash =  {price:game_price,name:game_name,platform:game_platform,link:game_link,image:game_image}
        @instant_game_array << hash

        count_elements = count_elements + 1
      end

      # puts '0000000000000000000000 INSTANT GAMING RESULT 00000000000000000000000000000000000'
      # puts instant_game_array
      # puts '00000000000000000000000000 END INSTANT GAMING RESULT 0000000000000000000000000000000'

    #KINGUIN SEARCH
      kinguin_page = mechanize.get('https://www.kinguin.net')
      search_input = kinguin_page.forms.first
      search_input['q'] = game_search_term
      kinguin_page = search_input.submit

      results = kinguin_page.at('.cat-v1')
      # offer_details = results.at('#offerDetails')

      games = results.search('.category')

      @kinguin_games_array = []

      games.each do |game|

        if game.at('.actual-price')
        game_price = game.at('.actual-price').text.strip
        game_name = game.at('.product-name').text.strip
        else
          next
        end

        game_platform_container = game.at('.properties')
        game_platform = game_platform_container.at('div')['title']

        game_link_container = game.at('.product-name')
        game_link_h4 = game_link_container.at('h4')
        game_link = game_link_h4.at('a')["href"]

        game_image_container = game.at('.main-image')
        game_image_array = game_image_container.search('img')[0]
        game_image = game_image_array['src']

        hash =  {price:game_price,name:game_name,platform:game_platform.remove('Platform: '),link:game_link,image:game_image}
        @kinguin_games_array << hash
      end

      # puts '0000000000000000000000 KINGUIN RESULT 00000000000000000000000000000000000'
      # puts kinguin_games_array
      # puts '00000000000000000000000000 END KINGUIN RESULT 0000000000000000000000000000000'

    #G2A SEARCH
      g2a_page = mechanize.get('https://www.g2a.com/')
      search_input = g2a_page.forms.first
      search_input['query'] = game_search_term
      g2a_page = search_input.submit

      results = g2a_page.at('.products-grid')
      games = results.search('li')

      @g2a_games_array = []

      games.each do |game|
        game_price = game.at('.Card__price').text.strip
        game_name = game.at('.Card__title').text.strip

        game_link_container = game.at('.Card__media')
        game_link = 'https://www.g2a.com' + game_link_container.at('a')['href']

        game_image = game.at('.Card__img.Card__img--placeholder')['src']

        hash =  {price:game_price,name:game_name,platform:nil,link:game_link,image:game_image}
        @g2a_games_array << hash

      end

      # puts '0000000000000000000000 G2A RESULT 00000000000000000000000000000000000'
      # puts g2a_games_array
      # puts '00000000000000000000000000 END G2A RESULT 0000000000000000000000000000000'

      # @sites_array = []
      #
      # instant_game_array.each do |instant|
      #   @sites_array << instant
      #   kinguin_games_array.each do |kinguin|
      #     @sites_array << kinguin
      #     g2a_games_array.each do |g2a|
      #       @sites_array << g2a
      #     end
      #   end
      # end

      # puts '0000000000000000000000 G2A RESULT 00000000000000000000000000000000000'
      # puts @sites_array
      # puts '00000000000000000000000000 END G2A RESULT 0000000000000000000000000000000'

    end

  end



  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :search, :kinguinPrice, :instantGamingPrice, :g2aPrice)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :game_name %>
  </div>

  <div class="field">
    <%= form.label :search %>
    <%= form.text_field :search, id: :game_search %>
  </div>

  <div class="field">
    <%= form.label :kinguinPrice %>
    <%= form.text_field :kinguinPrice, id: :game_kinguinPrice %>
  </div>

  <div class="field">
    <%= form.label :instantGamingPrice %>
    <%= form.text_field :instantGamingPrice, id: :game_instantGamingPrice %>
  </div>

  <div class="field">
    <%= form.label :g2aPrice %>
    <%= form.text_field :g2aPrice, id: :game_g2aPrice %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<nav class="light-blue lighten-1" role="navigation">
  <div class="nav-wrapper container"><a id="logo-container" href="<%= root_path %>" class="brand-logo">GamesCompare!</a>
    <ul class="right hide-on-med-and-down">
    </ul>

    <ul id="nav-mobile" class="side-nav" style="transform: translateX(-100%);">
    </ul>
  </div>
</nav>

<div class="section no-pad-bot" id="index-banner">
  <div class="container">
    <br><br>
    <h1 class="header center orange-text">
      <% if params[:game_search] %>
        Hai cercato <%= params[:game_search].capitalize %>
      <% else %>
        GamesCompare
      <% end %>
    </h1>
    <div class="row center">
      <h5 class="header col s12 light">Compara videogiochi</h5>
    </div>
    <div class="row center">
      <div class="input-field col s12">
        <%= form_tag(games_path, method: :get) do %>
          <%= text_field_tag :game_search, params[:game_search], class: 'validate center-align search-input', placeholder:'cerca un gioco' %>
        <% end %>
      </div>
    </div>
    <br><br>
  </div>
</div>

<div class="container">

  <% if params[:game_search] %>
    <div class="row">
      <h5 class="header col s12 m12 l12 light center-align orange-text">INSTANT GAMING</h5>
      <% @instant_game_array.each do |game| %>
        <div class="col s12 m6 l6">
          <div class="card horizontal">
            <div class="card-image">
              <img style="max-width: 100px;max-height: 190px" src="<%= game[:image] %>">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <p class="truncate"><b><%= game[:name] %></b></p>
                <br>
                <p>prezzo: <%= game[:price] %></p>
                <p>piattaforma: <%= game[:platform] %></p>
              </div>
              <div class="card-action">
                <a target="_blank" href="<%= game[:link] %>">Vai al gioco</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br><br>
    <div class="row">
      <h5 class="header col s12 m12 l12 light center-align orange-text">KINGUIN</h5>
      <% @kinguin_games_array.each do |game| %>
        <div class="col s12 m6 l6">
          <div class="card horizontal">
            <div class="card-image">
              <img style="max-width: 100px;max-height: 190px" src="<%= game[:image] %>">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <p class="truncate"><b><%= game[:name] %></b></p>
                <br>
                <p>prezzo: <%= game[:price] %></p>
                <p>piattaforma: <%= game[:platform] %></p>
              </div>
              <div class="card-action">
                <a target="_blank" href="<%= game[:link] %>">Vai al gioco</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br><br>
    <div class="row">
      <h5 class="header col s12 m12 l12 light center-align orange-text">G2A</h5>
      <% @g2a_games_array.each do |game| %>
        <div class="col s12 m6 l6">
          <div class="card horizontal">
            <div class="card-image">
              <img style="max-width: 100px;max-height: 190px" src="<%= game[:image] %>">
            </div>
            <div class="card-stacked">
              <div class="card-content">
                <p class="truncate"><b><%= game[:name] %></b></p>
                <br>
                <p>prezzo: <%= game[:price] %></p>
                <p>piattaforma: <%= game[:platform] %></p>
              </div>
              <div class="card-action">
                <a target="_blank" href="<%= game[:link] %>">Vai al gioco</a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<footer class="page-footer orange">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Company Bio</h5>
        <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>
      </div>
      <!--<div class="col l3 s12">-->
      <!--<h5 class="white-text">Settings</h5>-->
      <!--<ul>-->
      <!--<li><a class="white-text" href="#!">Link 1</a></li>-->
      <!--<li><a class="white-text" href="#!">Link 2</a></li>-->
      <!--<li><a class="white-text" href="#!">Link 3</a></li>-->
      <!--<li><a class="white-text" href="#!">Link 4</a></li>-->
      <!--</ul>-->
      <!--</div>-->
      <div class="col l3 s12">
        <h5 class="white-text">Connect</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
          <li><a class="white-text" href="#!">Link 2</a></li>
          <li><a class="white-text" href="#!">Link 3</a></li>
          <li><a class="white-text" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      Creato da Demone Scimmia 8
    </div>
  </div>
</footer>


<!--  Scripts-->
<div class="hiddendiv common"></div><div class="drag-target" data-sidenav="nav-mobile" style="left: 0px; touch-action: pan-y; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"></div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Search:</strong>
  <%= @game.search %>
</p>

<p>
  <strong>Kinguinprice:</strong>
  <%= @game.kinguinPrice %>
</p>

<p>
  <strong>Instantgamingprice:</strong>
  <%= @game.instantGamingPrice %>
</p>

<p>
  <strong>G2aprice:</strong>
  <%= @game.g2aPrice %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamescompare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>